name: Build and publish Dockerfile

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
      - 'src/**'
  pull_request:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    uses: Prism-Hosting/git-workflows/.github/workflows/docker-build.yml@main
    secrets: inherit